data1 = input("data1: ")
list1 = data1.split(",")
data2 = input("data2: ")
list2 = data2.split(",")
num = int(input("num: "))
print(list1 * num)
print(list2 * num)
list1.extend(list2)
print("extending list1 with list2:", list1)
